# Site settings
title: Sean Ballais
header-img: img/home-bg.jpg
email: sfballais123@gmail.com
description: "The personal website of Sean Francis N. Ballais"
baseurl: ""
url: "http://seanballais.tk"
twitter_username: seanballais
github_username:  seanballais
facebook_username: seanballais

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
