# Site settings
title: Sean Ballais
header-img: img/home-bg.jpg
email: sean@seanballais.com
description: "Coder, Blogger, Student"
baseurl: ""
url: "http://seanballais.com"
twitter_username: seanballais
github_username:  seanballais
facebook_username: seanballais
linkedin_username: seanballais
reddit_username: seanballais

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 3
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
future: true

gems:
  - jekyll-sitemap
  - jekyll-paginate
