title: Sean Ballais
email: sean@seanballais.com
baseurl: ""
url: "http://seanballais.com"
twitter_username: seanballais
github_username:  seanballais
facebook_username: seanballais
reddit_username: seanballais
linkedin_username: seanballais

permalink: pretty

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-github-metadata
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
  - raw
