title: Sean Ballais
email: sean@seanballais.com
description: "The personal website and blog of Sean Ballais, a programmer and CS student from Tacloban City, Philippines."
baseurl: ""
url: "http://seanballais.com"
twitter_username: seanballais
github_username:  seanballais
facebook_username: seanballais
reddit_username: seanballais
linkedin_username: seanballais

permalink: pretty
future: true

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-github-metadata
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
  - raw
